config/routes.rb
Rails.application.routes.draw do
  resources :end_documentations

  resources :doku_ids

  resources :w_numbers

  resources :orders

  resources :contactpeople

  resources :customers

  resources :end_documentations do
    member do
      put 'print'
    end
  end

end

app/models/w_number.rb
class WNumber < ActiveRecord::Base
	belongs_to :order

	def self.search(search)
		if search
			where(['number LIKE ?', "%#{search}%"])
		else
			all
		end
	end
end

app/controllers/w_numbers_controller.rb
class WNumbersController < ApplicationController
  before_action :set_w_number, only: [:show, :edit, :update, :destroy]

  # GET /w_numbers
  # GET /w_numbers.json

  def index
      @w_numbers = WNumber.search(params[:search])
    #@w_numbers = WNumber.all
  end

  # GET /w_numbers/1
  # GET /w_numbers/1.json
  def show
    @w_numbers = WNumber.find(params[:id])
    @order = Order.find(@w_numbers.order_id)
    @customer = Customer.find(@order.customer_id)
    begin
    @contact = Contactperson.find(@order.contactperson_id)
    rescue
    flash[:alert] = "keine Kontaktperson angegeben!"
  end
  end

  # GET /w_numbers/new
  def new
        @w_number = WNumber.new
  end

  # GET /w_numbers/1/edit
  def edit
  end

  # POST /w_numbers
  # POST /w_numbers.json
  def create
    @w_number = WNumber.new(w_number_params)

    respond_to do |format|
      if @w_number.save
        format.html { redirect_to @w_number, notice: 'W number was successfully created.' }
        format.json { render :show, status: :created, location: @w_number }
      else
        format.html { render :new }
        format.json { render json: @w_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /w_numbers/1
  # PATCH/PUT /w_numbers/1.json
  def update
    respond_to do |format|
      if @w_number.update(w_number_params)
        format.html { redirect_to @w_number, notice: 'W number was successfully updated.' }
        format.json { render :show, status: :ok, location: @w_number }
      else
        format.html { render :edit }
        format.json { render json: @w_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /w_numbers/1
  # DELETE /w_numbers/1.json
  def destroy
    @w_number.destroy
    respond_to do |format|
      format.html { redirect_to w_numbers_url, notice: 'W number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_w_number
      @w_number = WNumber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def w_number_params
      params.require(:w_number).permit(:number, :darwing_number, :year, :standard, :tag_number, :name, :order_id)
    end
end

app/helpers/w_numbers_helper.rb
module WNumbersHelper
end

app/views/w_numbers/_form.html.erb
<%= form_for(@w_number) do |f| %>
  <% if @w_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@w_number.errors.count, "error") %> prohibited this w_number from being saved:</h2>

      <ul>
      <% @w_number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :darwing_number %><br>
    <%= f.text_field :darwing_number %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :standard %><br>
    <%= f.text_field :standard %>
  </div>
  <div class="field">
    <%= f.label :tag_number %><br>
    <%= f.text_field :tag_number %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <% if params[:order_id] == NIL %>
        <%= f.number_field :order_id %>
    <% else %>
    <%= f.number_field :order_id , :value => params[:order_id]%>
    <%end %> 
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/w_numbers/edit.html.erb
<h1>Editing w_number</h1>

<%= render 'form' %>

<%= link_to 'Show', @w_number %> |
<%= link_to 'Back', w_numbers_path %>

app/views/w_numbers/index.html.erb
<h1>Listing w_numbers</h1>

<%= form_tag w_numbers_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Number</th>
      <th>Darwing number</th>
      <th>Year</th>
      <th>Standard</th>
      <th>Tag number</th>
      <th>Name</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @w_numbers.each do |w_number| %>
      <tr>
        <td><%= w_number.number %></td>
        <td><%= w_number.darwing_number %></td>
        <td><%= w_number.year %></td>
        <td><%= w_number.standard %></td>
        <td><%= w_number.tag_number %></td>
        <td><%= w_number.name %></td>
        <td><%= w_number.order_id %></td>
        <td><%= link_to 'Show', w_number %></td>
        <td><%= link_to 'Edit', edit_w_number_path(w_number) %></td>
        <td><%= link_to 'Destroy', w_number, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New W number', new_w_number_path %>

app/views/w_numbers/new.html.erb
<h1>New w_number</h1>

<%= render 'form' %>

<%= link_to 'Back', w_numbers_path %>

app/views/w_numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @w_number.number %>
</p>

<p>
  <strong>Darwing number:</strong>
  <%= @w_number.darwing_number %>
</p>

<p>
  <strong>Year:</strong>
  <%= @w_number.year %>
</p>

<p>
  <strong>Standard:</strong>
  <%= @w_number.standard %>
</p>

<p>
  <strong>Tag number:</strong>
  <%= @w_number.tag_number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @w_number.name %>
</p>

<p>
  <strong>Order:</strong>
  <%= @w_number.order_id %>
</p>

<%= @order.ext %>
<br/>
<%= link_to 'Edit', edit_w_number_path(@w_number) %> |
<%= link_to 'Back', w_numbers_path %>
<p><%= link_to "Printable (PDF)", w_number_path(@w_number, :format => 'pdf') %></p>