config/routes.rb
Rails.application.routes.draw do
  resources :end_documentations

  resources :doku_ids

  resources :w_numbers

  resources :orders

  resources :contactpeople

  resources :customers

  resources :end_documentations do
    member do
      put 'print'
    end
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :customer
	belongs_to :contactperson
	has_many :w_numbers
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
        @w_numbers = WNumber.where("order_id = ?", @order.id) 
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:apl, :ext, :customer_id, :contactperson_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :apl %><br>
    <%= f.text_field :apl %>
  </div>
  <div class="field">
    <%= f.label :ext %><br> 
    <%= f.text_field :ext %>
  </div>
  <div class="field">
    <%= f.label 'customer id' %><br>
    <% if params[:customer] == NIL %>
        <%= f.number_field :customer_id %>
    <% else %>
        <%= f.number_field :customer_id, :value => params[:customer]  %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :contactperson_id %><br>
    <%= f.number_field :contactperson_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
apl<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Apl</th>
      <th>Ext</th>
      <th>Customer</th>
      <th>Contactperson</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<table class="table table-striped">
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.apl %></td>
        <td><%= order.ext %></td>
        <td><%= order.customer_id %></td>
        <td><%= order.contactperson_id %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Apl:</strong>
  <%= @order.apl %>
</p>

<p>
  <strong>Ext:</strong>
  <%= @order.ext %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @order.customer_id %>
</p>

<p>
  <strong>Contactperson:</strong>
  <%= @order.contactperson_id %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>
<%= link_to 'New Product for this Customer', new_w_number_path(:order_id => @order.id) %>

<p> <br/> <br/> </p>

<%= form_tag print_end_documentation_path, :method => :put do %>
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Number</th>
      <th>Darwing number</th>
      <th>Year</th>
      <th>Standard</th>
      <th>Tag number</th>
      <th>Name</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @w_numbers.each do |w_number| %>
      <tr>
        <td><%= check_box_tag "w_number_ids[]", w_number.id %></td>
        <td><%= w_number.number %></td>
        <td><%= w_number.darwing_number %></td>
        <td><%= w_number.year %></td>
        <td><%= w_number.standard %></td>
        <td><%= w_number.tag_number %></td>
        <td><%= w_number.name %></td>
        <td><%= w_number.order_id %></td>
        <td><%= link_to 'Show', w_number %></td>
        <td><%= link_to 'Edit', edit_w_number_path(w_number) %></td>
        <td><%= link_to 'Destroy', w_number, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>        
  </tbody>
</table>
  <h3> Optionen: </h3>
  <h4> Entwurfsprüfung (Anschreiben) erstellen:</h4>
   Anzahl der CDs <%= number_field_tag :cd_value %> Anzahl der Kopien: <%= number_field_tag  :copy_value %> Sprache <%= text_field_tag :language %> Erstellt von <%= text_field_tag :user %> <%= submit_tag("Erstellen") %> 
<% end %>