config/routes.rb
Rails.application.routes.draw do
  resources :end_documentations

  resources :doku_ids

  resources :w_numbers

  resources :orders

  resources :contactpeople

  resources :customers

  resources :end_documentations do
    member do
      put 'print'
    end
  end

end

app/models/doku_id.rb
class DokuId < ActiveRecord::Base
end

app/controllers/doku_i_ds_controller.rb
class DokuIDsController < ApplicationController
  before_action :set_doku_id, only: [:show, :edit, :update, :destroy]

  # GET /doku_ids
  # GET /doku_ids.json
  def index
    @doku_ids = DokuId.all
  end

  # GET /doku_ids/1
  # GET /doku_ids/1.json
  def show
  end

  # GET /doku_ids/new
  def new
    @doku_id = DokuId.new
  end

  # GET /doku_ids/1/edit
  def edit
  end

  # POST /doku_ids
  # POST /doku_ids.json
  def create
    @doku_id = DokuId.new(doku_id_params)

    respond_to do |format|
      if @doku_id.save
        format.html { redirect_to @doku_id, notice: 'Doku was successfully created.' }
        format.json { render :show, status: :created, location: @doku_id }
      else
        format.html { render :new }
        format.json { render json: @doku_id.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doku_ids/1
  # PATCH/PUT /doku_ids/1.json
  def update
    respond_to do |format|
      if @doku_id.update(doku_id_params)
        format.html { redirect_to @doku_id, notice: 'Doku was successfully updated.' }
        format.json { render :show, status: :ok, location: @doku_id }
      else
        format.html { render :edit }
        format.json { render json: @doku_id.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doku_ids/1
  # DELETE /doku_ids/1.json
  def destroy
    @doku_id.destroy
    respond_to do |format|
      format.html { redirect_to doku_ids_url, notice: 'Doku was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doku_id
      @doku_id = DokuId.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doku_id_params
      params.require(:doku_id).permit(:w_number_id, :dokument_id)
    end
end

app/helpers/doku_i_ds_helper.rb
module DokuIDsHelper
end

app/views/doku_i_ds/_form.html.erb
<%= form_for(@doku_id) do |f| %>
  <% if @doku_id.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doku_id.errors.count, "error") %> prohibited this doku_id from being saved:</h2>

      <ul>
      <% @doku_id.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :w_number_id %><br>
    <%= f.number_field :w_number_id %>
  </div>
  <div class="field">
    <%= f.label :dokument_id %><br>
    <%= f.number_field :dokument_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doku_i_ds/edit.html.erb
<h1>Editing doku_id</h1>

<%= render 'form' %>

<%= link_to 'Show', @doku_id %> |
<%= link_to 'Back', doku_ids_path %>

app/views/doku_i_ds/index.html.erb
<h1>Listing doku_ids</h1>

<table>
  <thead>
    <tr>
      <th>W number</th>
      <th>Dokument</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doku_ids.each do |doku_id| %>
      <tr>
        <td><%= doku_id.w_number_id %></td>
        <td><%= doku_id.dokument_id %></td>
        <td><%= link_to 'Show', doku_id %></td>
        <td><%= link_to 'Edit', edit_doku_id_path(doku_id) %></td>
        <td><%= link_to 'Destroy', doku_id, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doku', new_doku_id_path %>

app/views/doku_i_ds/new.html.erb
<h1>New doku_id</h1>

<%= render 'form' %>

<%= link_to 'Back', doku_ids_path %>

app/views/doku_i_ds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>W number:</strong>
  <%= @doku_id.w_number_id %>
</p>

<p>
  <strong>Dokument:</strong>
  <%= @doku_id.dokument_id %>
</p>

<%= link_to 'Edit', edit_doku_id_path(@doku_id) %> |
<%= link_to 'Back', doku_ids_path %>